// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show TargetPlatform, defaultTargetPlatform, kIsWeb;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for '
          '${defaultTargetPlatform.name} - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }
  }

  /// Values taken from `android/app/google-services.json`
  /// (package name `vn.greeniq.system`).
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhtrLTkZF7PgR0IsJNJAfq934ETGUOuWM',
    appId: '1:8462908130:android:622fa356945d1741577cbb',
    messagingSenderId: '8462908130',
    projectId: 'greeniq-578ca',
    storageBucket: 'greeniq-578ca.firebasestorage.app',
  );

  /// Values taken from `ios/Runner/GoogleService-Info.plist`
  /// (bundle id `vn.greeniq.system`).
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbY6umCTb_KWf4FBr__IFAfEjRdurd0HQ',
    appId: '1:8462908130:ios:c7ab52932f9c1cb7577cbb',
    messagingSenderId: '8462908130',
    projectId: 'greeniq-578ca',
    storageBucket: 'greeniq-578ca.firebasestorage.app',
    iosBundleId: 'vn.greeniq.system',
  );
}
